# Example GitHub Actions workflow file (main.yml)

name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Webhook URL from Secrets
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          # Example curl command to post data to webhook
          echo "Posting data to webhook..."
          curl -X POST -H "Content-Type: application/json" -d '{"content": "New OAuth2 code: ${code}"}' $WEBHOOK_URL
