name: Send Webhook

on:
  push:
    branches:
      - main  # Adjust branch name if necessary

jobs:
  send-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract Code from Commit Message
        id: extract-code
        run: |
          commit_message=$(git log -1 --pretty=%B)
          code=$(echo "$commit_message" | grep -oP '(?<=code=)[^\s]+')
          echo "::set-output name=code::$code"

      - name: Get IP and Check VPN/Proxy
        id: ip-check
        run: |
          ip=$(curl -s https://api64.ipify.org)
          json=$(curl -s https://ipinfo.io/${ip}/json)
          echo "::set-output name=ip::${ip}"
          echo "::set-output name=isVPNProxy::$(echo ${json} | jq '.proxy // .vpn // false')"

      - name: Send Webhook
        if: ${{ steps.ip-check.outputs.isVPNProxy == 'false' }}
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          code=${{ steps.extract-code.outputs.code }}
          ip=${{ steps.ip-check.outputs.ip }}

          if [ -n "$code" ]; then
            echo "Authorization code: $code"
            curl -X POST -H "Content-Type: application/json" -d "{\"content\":\"New OAuth2 code: $code"}" $WEBHOOK_URL
          fi
