name: Send Webhook

on:
  push:
    branches:
      - main  # Adjust branch name if necessary

jobs:
  send-webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment variables
      run: |
        echo "WEBHOOK_URL=${{ secrets.WEBHOOK_URL }}" >> $GITHUB_ENV

    - name: Extract code from commit message
      id: extract-code
      run: |
        commit_message=$(git log -1 --pretty=%B)
        code=$(echo "$commit_message" | grep -oP '(?<=code=)[^\s]+')
        echo "::set-output name=code::$code"

    - name: Execute send_webhook script
      if: steps.extract-code.outputs.code != ''
      run: |
        code=${{ steps.extract-code.outputs.code }}
        ip=$(curl -s https://api64.ipify.org)

        echo "Authorization code: $code"
        curl -X POST -H "Content-Type: application/json" -d "{\"content\":\"New OAuth2 code: $code\"}" $WEBHOOK_URL
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
