name: Send Webhook

on:
  push:
    branches:
      - main  # Adjust branch name if necessary

jobs:
  send-webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment variables
      run: |
        echo "WEBHOOK_URL=${{ secrets.WEBHOOK_URL }}" >> $GITHUB_ENV

    - name: Execute send_webhook script
      run: |
        code="abcdef123456"  # Replace with your code extraction logic
        ip=$(curl -s https://api64.ipify.org)

        if [ -n "$code" ]; then
          echo "Authorization code: $code"
          curl -X POST -H "Content-Type: application/json" -d "{\"content\":\"New OAuth2 code: $code\"}" $WEBHOOK_URL
        fi
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
